/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login_gestionstock (void);
GtkWidget* create_Login_bienvenue (void);
GtkWidget* create_Ajout_produit (void);
GtkWidget* create_Stock (void);
GtkWidget* create_Modification (void);
GtkWidget* create_rupture (void);
GtkWidget* create_confirmer_suppr (void);
